spring:
  application:
    name: catalog-service

server:
  port: 8080
  tomcat:
    #    It helps prevent denial-of-service (DoS) attacks where a
    #    connection is established, Tomcat reserves a thread to handle the
    #    request, and the request never comes. The same timeout is used to
    #    limit the time spent reading the HTTP request body when there is
    #    one.
    connection-timeout: 20s
    #    property to conﬁgure how long to keep a connection open
    #    while waiting for new HTTP requests.
    keep-alive-timeout: 15s
    threads:
      #    The number of available threads will
      #    determine how many requests can be handled simultaneously
      max: 200
      #      how many threads are created at startup
      min-spare: 10